from django.core.management.base import BaseCommand
from store.models import Category, Product
import random


class Command(BaseCommand):
    help = 'Populate database with realistic products for each category'

    def handle(self, *args, **kwargs):
        # Product data by category
        products_data = {
            "Women's Apparel": [
                {"name": "Floral Summer Dress", "price": 49.99, "desc": "Lightweight floral print dress perfect for summer outings", "specs": "Material: Cotton blend, Available sizes: XS-XL"},
                {"name": "Classic Denim Jacket", "price": 79.99, "desc": "Timeless denim jacket with button closure", "specs": "100% Cotton, Classic fit, Machine washable"},
                {"name": "Silk Blouse", "price": 39.99, "desc": "Elegant silk blouse for office or casual wear", "specs": "Material: 100% Silk, Dry clean only"},
                {"name": "High-Waisted Jeans", "price": 59.99, "desc": "Comfortable high-waisted skinny jeans", "specs": "Stretch denim, Multiple washes available"},
                {"name": "Leather Ankle Boots", "price": 89.99, "desc": "Genuine leather ankle boots with side zip", "specs": "Genuine leather, 2-inch heel, Cushioned insole"},
                {"name": "Cashmere Sweater", "price": 99.99, "desc": "Luxurious cashmere pullover sweater", "specs": "100% Cashmere, Hand wash recommended"},
                {"name": "Maxi Skirt", "price": 44.99, "desc": "Flowing maxi skirt with elastic waistband", "specs": "Polyester blend, Machine washable, Multiple colors"},
                {"name": "Blazer", "price": 89.99, "desc": "Tailored blazer for professional look", "specs": "Polyester/Wool blend, Dry clean only"},
                {"name": "Yoga Pants", "price": 34.99, "desc": "High-performance yoga pants with moisture wicking", "specs": "Spandex blend, 4-way stretch, Quick dry"},
                {"name": "Cardigan", "price": 45.99, "desc": "Cozy knit cardigan with pockets", "specs": "Acrylic/Cotton blend, Machine washable"},
                {"name": "Tank Top Set", "price": 29.99, "desc": "Pack of 3 basic tank tops", "specs": "95% Cotton, 5% Spandex, Multiple colors"},
                {"name": "Midi Dress", "price": 54.99, "desc": "Elegant midi dress for special occasions", "specs": "Polyester, Side zipper, Lined"},
                {"name": "Leggings", "price": 24.99, "desc": "High-waisted compression leggings", "specs": "Nylon/Spandex blend, Squat proof, Pocket"},
                {"name": "Trench Coat", "price": 119.99, "desc": "Classic trench coat with belt", "specs": "Water-resistant, Removable lining, Double-breasted"},
                {"name": "Wrap Dress", "price": 64.99, "desc": "Flattering wrap dress with tie waist", "specs": "Jersey knit, Machine washable, Versatile style"},
                {"name": "Palazzo Pants", "price": 42.99, "desc": "Wide-leg palazzo pants", "specs": "Rayon blend, Elastic waist, Flowy fit"},
                {"name": "Turtleneck Top", "price": 32.99, "desc": "Long sleeve turtleneck top", "specs": "Ribbed knit, Stretchy, Multiple colors"},
                {"name": "Cocktail Dress", "price": 74.99, "desc": "Stunning cocktail dress with sequin detail", "specs": "Polyester/Spandex, Back zipper, Party wear"},
                {"name": "Capri Pants", "price": 38.99, "desc": "Comfortable capri pants", "specs": "Cotton/Spandex, Cropped length, Casual fit"},
                {"name": "Kimono Robe", "price": 36.99, "desc": "Lightweight kimono-style robe", "specs": "Satin, Tie closure, Versatile layering piece"},
            ],
            "Mobile & Gadgets": [
                {"name": "Smartphone X Pro", "price": 899.99, "desc": "Latest flagship smartphone with AI camera", "specs": "6.7\" AMOLED, 256GB, 5G, Triple camera 108MP"},
                {"name": "Wireless Earbuds Pro", "price": 149.99, "desc": "Premium wireless earbuds with ANC", "specs": "Active Noise Cancellation, 30hr battery, IPX4"},
                {"name": "Smartwatch Series 7", "price": 399.99, "desc": "Advanced smartwatch with health tracking", "specs": "AMOLED display, Heart rate monitor, GPS, 5ATM"},
                {"name": "Portable Charger 20000mAh", "price": 39.99, "desc": "High-capacity portable power bank", "specs": "20000mAh, Fast charging, Dual USB ports, LED display"},
                {"name": "Bluetooth Speaker Portable", "price": 79.99, "desc": "Waterproof portable Bluetooth speaker", "specs": "360° sound, 12hr battery, IPX7 waterproof"},
                {"name": "Phone Case Protective Set", "price": 19.99, "desc": "Protective phone case with screen protector", "specs": "Shockproof, Military grade, Wireless charging compatible"},
                {"name": "Tablet 10.5 inch", "price": 449.99, "desc": "High-performance tablet for work and play", "specs": "10.5\" display, 128GB, Octa-core, 8GB RAM"},
                {"name": "Wireless Charger Pad", "price": 29.99, "desc": "Fast wireless charging pad", "specs": "15W fast charge, Universal compatibility, LED indicator"},
                {"name": "USB-C Hub Adapter", "price": 49.99, "desc": "Multi-port USB-C hub adapter", "specs": "7-in-1, HDMI 4K, USB 3.0, SD card reader"},
                {"name": "Phone Gimbal Stabilizer", "price": 89.99, "desc": "3-axis smartphone gimbal for smooth video", "specs": "Foldable, 12hr runtime, Face tracking, 280g payload"},
                {"name": "Magnetic Phone Mount", "price": 24.99, "desc": "Magnetic car phone holder", "specs": "360° rotation, Strong magnet, Dashboard/vent mount"},
                {"name": "Screen Protector Pack", "price": 14.99, "desc": "Tempered glass screen protectors (3-pack)", "specs": "9H hardness, Anti-fingerprint, Bubble-free installation"},
                {"name": "Pop Socket Grip", "price": 9.99, "desc": "Collapsible phone grip and stand", "specs": "Reusable adhesive, Swappable top, Multiple designs"},
                {"name": "Selfie Ring Light", "price": 19.99, "desc": "Clip-on LED ring light", "specs": "3 light modes, Rechargeable, 360° rotation"},
                {"name": "Gaming Phone Cooler", "price": 34.99, "desc": "Phone cooling fan for gaming", "specs": "Semiconductor cooling, 7-blade fan, RGB lighting"},
                {"name": "Stylus Pen Digital", "price": 44.99, "desc": "Precision stylus for tablets", "specs": "Palm rejection, Tilt sensitivity, 12hr battery"},
                {"name": "VR Headset Mobile", "price": 299.99, "desc": "Virtual reality headset for smartphones", "specs": "110° FOV, Adjustable lenses, Compatible 4.7-6.5\" phones"},
                {"name": "Phone Sanitizer UV-C", "price": 49.99, "desc": "UV-C phone sanitizer and charger", "specs": "99.9% germ elimination, Wireless charging, 10min cycle"},
                {"name": "Camera Lens Kit Phone", "price": 39.99, "desc": "3-in-1 phone camera lens attachment", "specs": "Wide angle, Macro, Fisheye, Universal clip"},
                {"name": "Bluetooth Tracker Tag", "price": 24.99, "desc": "Item tracker with smartphone app", "specs": "Bluetooth 5.0, 200ft range, Replaceable battery"},
            ],
            "Computers & Peripherals": [
                {"name": "Gaming Laptop 15.6\"", "price": 1299.99, "desc": "High-performance gaming laptop", "specs": "RTX 4060, Intel i7, 16GB RAM, 512GB SSD, 144Hz display"},
                {"name": "Mechanical Keyboard RGB", "price": 89.99, "desc": "RGB mechanical gaming keyboard", "specs": "Cherry MX switches, Programmable keys, Aluminum frame"},
                {"name": "Wireless Gaming Mouse", "price": 69.99, "desc": "Ergonomic wireless gaming mouse", "specs": "20000 DPI, 70hr battery, 8 programmable buttons"},
                {"name": "27\" 4K Monitor", "price": 449.99, "desc": "Ultra HD 4K monitor for professionals", "specs": "27\" IPS, 4K UHD, 99% sRGB, HDR10, USB-C"},
                {"name": "Webcam 1080p", "price": 79.99, "desc": "Full HD webcam with auto-focus", "specs": "1080p 60fps, Dual microphones, Auto light correction"},
                {"name": "External SSD 1TB", "price": 129.99, "desc": "Portable solid state drive", "specs": "1TB, USB 3.2, 1050MB/s read, Shock resistant"},
                {"name": "USB Microphone", "price": 99.99, "desc": "Professional USB condenser microphone", "specs": "Cardioid pattern, Plug & play, Mute button, Headphone jack"},
                {"name": "Laptop Stand", "price": 34.99, "desc": "Aluminum adjustable laptop stand", "specs": "Adjustable height, Cooling design, Universal fit"},
                {"name": "Wireless Keyboard & Mouse Combo", "price": 49.99, "desc": "Slim wireless keyboard and mouse set", "specs": "2.4GHz wireless, 36-month battery, Quiet keys"},
                {"name": "Graphics Drawing Tablet", "price": 199.99, "desc": "Digital drawing tablet with pen", "specs": "10×6\" active area, 8192 pressure levels, Battery-free pen"},
                {"name": "Docking Station", "price": 159.99, "desc": "Universal laptop docking station", "specs": "Dual 4K HDMI, 100W charging, 10 ports, Thunderbolt 3"},
                {"name": "Webcam Cover", "price": 8.99, "desc": "Privacy webcam cover (6-pack)", "specs": "Ultra-thin, Universal fit, Easy slide mechanism"},
                {"name": "Mouse Pad XXL", "price": 24.99, "desc": "Extended gaming mouse pad", "specs": "35×15\", Non-slip rubber base, Waterproof surface"},
                {"name": "Cable Management Box", "price": 19.99, "desc": "Cable organizer box", "specs": "Holds power strips, Flame resistant, Multiple openings"},
                {"name": "Monitor Arm Mount", "price": 89.99, "desc": "Dual monitor desk mount", "specs": "Supports 2×27\", Gas spring, 360° rotation, VESA compatible"},
                {"name": "Laptop Cooling Pad", "price": 29.99, "desc": "Laptop cooler with 5 fans", "specs": "5 quiet fans, Adjustable height, Dual USB ports"},
                {"name": "KVM Switch", "price": 44.99, "desc": "4-port KVM switch", "specs": "Share keyboard/mouse/monitor, 4K support, Hotkey switching"},
                {"name": "RAM 16GB DDR4", "price": 64.99, "desc": "Desktop memory upgrade kit", "specs": "16GB (2×8GB), DDR4 3200MHz, CL16, Heat spreader"},
                {"name": "Bluetooth Adapter", "price": 12.99, "desc": "USB Bluetooth 5.0 adapter", "specs": "Bluetooth 5.0, 20m range, Plug & play, Low energy"},
                {"name": "HDMI Cable 6ft", "price": 14.99, "desc": "High-speed HDMI 2.1 cable", "specs": "4K 120Hz, 8K 60Hz, eARC, Braided, Gold-plated"},
            ],
            "Home Appliances": [
                {"name": "Air Fryer 5.8 Quart", "price": 89.99, "desc": "Digital air fryer with 8 presets", "specs": "5.8Qt capacity, 1700W, Non-stick basket, Dishwasher safe"},
                {"name": "Robot Vacuum Cleaner", "price": 299.99, "desc": "Smart robot vacuum with mapping", "specs": "2700Pa suction, LiDAR navigation, 150min runtime, App control"},
                {"name": "Coffee Maker 12-Cup", "price": 79.99, "desc": "Programmable drip coffee maker", "specs": "12-cup capacity, Auto brew, Keep warm, Reusable filter"},
                {"name": "Blender 1400W", "price": 129.99, "desc": "High-performance blender", "specs": "1400W motor, 64oz pitcher, Variable speed, Pulse function"},
                {"name": "Electric Kettle", "price": 39.99, "desc": "Stainless steel electric kettle", "specs": "1.7L, 1500W, Auto shut-off, Boil-dry protection"},
                {"name": "Toaster Oven", "price": 119.99, "desc": "Convection toaster oven", "specs": "6 slice capacity, Convection, 1800W, 10 functions"},
                {"name": "Stand Mixer", "price": 199.99, "desc": "Electric stand mixer", "specs": "5Qt bowl, 10 speeds, Planetary mixing, 3 attachments"},
                {"name": "Microwave Oven", "price": 149.99, "desc": "Countertop microwave", "specs": "1.1 cu ft, 1000W, 10 power levels, Express cook"},
                {"name": "Slow Cooker 6-Quart", "price": 49.99, "desc": "Programmable slow cooker", "specs": "6Qt capacity, Digital timer, Warm function, Dishwasher safe"},
                {"name": "Food Processor", "price": 89.99, "desc": "12-cup food processor", "specs": "12-cup capacity, 720W, Multiple blades, BPA-free"},
                {"name": "Electric Pressure Cooker", "price": 99.99, "desc": "Multi-function pressure cooker", "specs": "6Qt, 14 programs, Slow cook, Rice cooker, Steamer"},
                {"name": "Hand Mixer", "price": 34.99, "desc": "Electric hand mixer", "specs": "250W, 5 speeds, Turbo boost, Beaters & dough hooks"},
                {"name": "Rice Cooker 10-Cup", "price": 44.99, "desc": "Automatic rice cooker", "specs": "10-cup capacity, Keep warm, Steam tray, Non-stick pot"},
                {"name": "Juicer", "price": 79.99, "desc": "Centrifugal juicer", "specs": "Wide mouth, Dual speed, 800W, Easy clean, BPA-free"},
                {"name": "Waffle Maker", "price": 29.99, "desc": "Belgian waffle maker", "specs": "Non-stick plates, Adjustable temperature, Ready indicator"},
                {"name": "Immersion Blender", "price": 39.99, "desc": "Hand blender with accessories", "specs": "500W, Variable speed, Whisk & chopper attachments"},
                {"name": "Bread Maker", "price": 119.99, "desc": "Automatic bread machine", "specs": "2lb capacity, 12 programs, Delay timer, Non-stick pan"},
                {"name": "Electric Grill", "price": 69.99, "desc": "Indoor electric grill", "specs": "1800W, Non-stick grill plates, Adjustable temperature"},
                {"name": "Ice Cream Maker", "price": 49.99, "desc": "Electric ice cream maker", "specs": "1.5Qt capacity, 20min operation, BPA-free bowl"},
                {"name": "Dehydrator", "price": 64.99, "desc": "Food dehydrator", "specs": "5 trays, Adjustable temperature, Quiet operation, BPA-free"},
            ],
            "Food & Beverages": [
                {"name": "Organic Coffee Beans 2lb", "price": 24.99, "desc": "Premium organic whole bean coffee", "specs": "100% Arabica, Medium roast, Fair trade, Single origin"},
                {"name": "Green Tea Variety Pack", "price": 18.99, "desc": "Assorted green tea collection", "specs": "60 tea bags, 6 flavors, Organic, Antioxidant rich"},
                {"name": "Gourmet Dark Chocolate", "price": 12.99, "desc": "Artisan dark chocolate bar set", "specs": "70% cacao, 6 bars, Organic, Non-GMO"},
                {"name": "Extra Virgin Olive Oil", "price": 19.99, "desc": "Cold-pressed olive oil", "specs": "500ml, First cold press, Italian, Glass bottle"},
                {"name": "Protein Powder Vanilla", "price": 34.99, "desc": "Whey protein isolate", "specs": "2lb, 25g protein per serving, Grass-fed, Low carb"},
                {"name": "Organic Honey", "price": 16.99, "desc": "Raw unfiltered honey", "specs": "16oz, Raw & unfiltered, No additives, Glass jar"},
                {"name": "Mixed Nuts Bulk Pack", "price": 22.99, "desc": "Premium mixed nuts", "specs": "2lb, Unsalted, Roasted, Almonds/cashews/pecans"},
                {"name": "Matcha Green Tea Powder", "price": 19.99, "desc": "Ceremonial grade matcha", "specs": "100g, Ceremonial grade, Japanese, Antioxidant"},
                {"name": "Coconut Oil", "price": 14.99, "desc": "Organic virgin coconut oil", "specs": "16oz, Cold-pressed, Unrefined, Multi-purpose"},
                {"name": "Chia Seeds", "price": 11.99, "desc": "Organic chia seeds", "specs": "2lb, Organic, Omega-3, High fiber, Gluten-free"},
                {"name": "Almond Butter", "price": 13.99, "desc": "Organic almond butter", "specs": "16oz, Organic, No salt/sugar added, Creamy"},
                {"name": "Quinoa", "price": 15.99, "desc": "Organic white quinoa", "specs": "2lb, Organic, Pre-washed, High protein, Gluten-free"},
                {"name": "Himalayan Pink Salt", "price": 9.99, "desc": "Fine grain pink salt", "specs": "1lb, 84 trace minerals, Fine grain, Grinder"},
                {"name": "Apple Cider Vinegar", "price": 12.99, "desc": "Organic ACV with mother", "specs": "32oz, Organic, Unfiltered, Raw, Glass bottle"},
                {"name": "Dark Roast Coffee K-Cups", "price": 29.99, "desc": "Single-serve coffee pods", "specs": "80 count, Dark roast, Compatible, Recyclable"},
                {"name": "Energy Bar Variety", "price": 19.99, "desc": "Protein energy bars", "specs": "20 bars, 10g protein, Gluten-free, 5 flavors"},
                {"name": "Herbal Tea Sampler", "price": 16.99, "desc": "Caffeine-free herbal tea set", "specs": "48 tea bags, 8 flavors, Organic, Bedtime blend"},
                {"name": "Maple Syrup Pure", "price": 21.99, "desc": "100% pure maple syrup", "specs": "16oz, Grade A, Amber color, Canadian, Glass bottle"},
                {"name": "Beef Jerky", "price": 18.99, "desc": "Premium grass-fed beef jerky", "specs": "8oz, Grass-fed, High protein, No MSG, Gluten-free"},
                {"name": "Sparkling Water 24-Pack", "price": 14.99, "desc": "Naturally flavored sparkling water", "specs": "24 cans, Zero calories, No sweeteners, 4 flavors"},
            ],
            "Kids Fashion": [
                {"name": "Kids Sneakers Light-Up", "price": 34.99, "desc": "LED light-up sneakers for kids", "specs": "Sizes 10-3, Velcro closure, LED lights, Durable sole"},
                {"name": "Girls Tutu Dress", "price": 29.99, "desc": "Princess tutu dress with sequins", "specs": "Ages 3-8, Polyester, Multiple colors, Machine washable"},
                {"name": "Boys Graphic Tee Set", "price": 24.99, "desc": "Pack of 5 graphic t-shirts", "specs": "100% cotton, Short sleeve, Fun designs, Sizes 4-12"},
                {"name": "Kids Rain Boots", "price": 22.99, "desc": "Waterproof rain boots", "specs": "Sizes 8-2, Waterproof, Non-slip, Fun patterns"},
                {"name": "Toddler Pajama Set", "price": 19.99, "desc": "Two-piece pajama set", "specs": "100% cotton, Flame resistant, Snug fit, Sizes 2T-5T"},
                {"name": "Kids Winter Jacket", "price": 49.99, "desc": "Insulated winter coat", "specs": "Water resistant, Hood, Puffer style, Sizes 4-14"},
                {"name": "Baby Onesie 5-Pack", "price": 18.99, "desc": "Short sleeve bodysuits", "specs": "100% cotton, Snap closure, Multiple colors, 0-24M"},
                {"name": "Girls Leggings Set", "price": 21.99, "desc": "3-pack cotton leggings", "specs": "95% cotton, Elastic waist, Solid colors, Sizes 4-12"},
                {"name": "Boys Cargo Shorts", "price": 26.99, "desc": "Adjustable waist cargo shorts", "specs": "Cotton blend, Multiple pockets, Adjustable waist, 4-16"},
                {"name": "Kids Backpack", "price": 29.99, "desc": "School backpack with lunch bag", "specs": "16\", Water resistant, Padded straps, Fun designs"},
                {"name": "Baby Socks 12-Pack", "price": 12.99, "desc": "Non-slip baby socks", "specs": "Anti-slip grip, Cotton blend, Multiple colors, 0-12M"},
                {"name": "Kids Sun Hat", "price": 14.99, "desc": "Wide brim sun protection hat", "specs": "UPF 50+, Adjustable strap, Breathable, Multiple sizes"},
                {"name": "Girls Dress Shoes", "price": 32.99, "desc": "Mary Jane style dress shoes", "specs": "Patent leather, Velcro strap, Cushioned, Sizes 9-3"},
                {"name": "Boys Swim Trunks", "price": 19.99, "desc": "Quick-dry swim shorts", "specs": "Polyester, Elastic waist, Mesh lining, Sizes 4-14"},
                {"name": "Kids Fleece Hoodie", "price": 27.99, "desc": "Zip-up fleece hoodie", "specs": "Soft fleece, Front pockets, Full zipper, Sizes 4-14"},
                {"name": "Baby Bibs 10-Pack", "price": 15.99, "desc": "Waterproof baby bibs", "specs": "Waterproof layer, Velcro closure, Machine washable"},
                {"name": "Girls Hair Accessories", "price": 16.99, "desc": "Hair bow and clip set", "specs": "40 pieces, Various styles, Non-slip, Bright colors"},
                {"name": "Boys Athletic Shorts", "price": 22.99, "desc": "Moisture-wicking gym shorts", "specs": "Polyester, Elastic waist, Side pockets, Sizes 4-16"},
                {"name": "Kids Sandals", "price": 24.99, "desc": "Adjustable strap sandals", "specs": "Velcro straps, Cushioned sole, Water-friendly, 8-3"},
                {"name": "Baby Sleep Sack", "price": 21.99, "desc": "Wearable blanket sleeper", "specs": "TOG 2.5, Sleeveless, Zipper, 100% cotton, 0-24M"},
            ],
            "Sports & Outdoors": [
                {"name": "Yoga Mat Premium", "price": 34.99, "desc": "Non-slip exercise yoga mat", "specs": "6mm thick, Non-slip surface, 72×24\", Carry strap"},
                {"name": "Resistance Bands Set", "price": 24.99, "desc": "Workout resistance bands", "specs": "5 resistance levels, Door anchor, Handles, Carry bag"},
                {"name": "Camping Tent 4-Person", "price": 129.99, "desc": "Easy setup camping tent", "specs": "4-person capacity, Waterproof, Easy setup, Carry bag"},
                {"name": "Adjustable Dumbbells", "price": 299.99, "desc": "Space-saving dumbbell set", "specs": "5-52.5lbs per dumbbell, Quick adjustment, Stand included"},
                {"name": "Hiking Backpack 40L", "price": 89.99, "desc": "Outdoor hiking backpack", "specs": "40L capacity, Rain cover, Hydration compatible, Ergonomic"},
                {"name": "Sleeping Bag", "price": 49.99, "desc": "3-season camping sleeping bag", "specs": "Temperature rated 20°F, Compression sack, Zipper guard"},
                {"name": "Bicycle Helmet", "price": 44.99, "desc": "Adult bike helmet with LED", "specs": "CPSC certified, Adjustable fit, Rear LED light, Vents"},
                {"name": "Water Bottle 32oz", "price": 29.99, "desc": "Insulated stainless steel bottle", "specs": "32oz, Double-wall vacuum, Leak-proof, 24hr cold"},
                {"name": "Jump Rope", "price": 14.99, "desc": "Adjustable speed jump rope", "specs": "Ball bearings, Adjustable length, Foam handles, Counter"},
                {"name": "Camping Chair", "price": 39.99, "desc": "Portable folding camping chair", "specs": "300lb capacity, Cup holder, Carry bag, Compact"},
                {"name": "Foam Roller", "price": 19.99, "desc": "Muscle massage foam roller", "specs": "13×6\", High-density foam, Textured surface, Exercises"},
                {"name": "Trekking Poles", "price": 34.99, "desc": "Collapsible hiking poles", "specs": "Aluminum, Adjustable 24-53\", Cork grips, Carry bag"},
                {"name": "Headlamp LED", "price": 22.99, "desc": "Rechargeable LED headlamp", "specs": "1000 lumens, USB rechargeable, Waterproof, Red light"},
                {"name": "Fishing Rod Combo", "price": 59.99, "desc": "Spinning rod and reel combo", "specs": "6'6\" medium, Pre-spooled, Tackle box included"},
                {"name": "Bike Lock", "price": 29.99, "desc": "Heavy-duty bike U-lock", "specs": "Hardened steel, 14mm shackle, 2 keys, Mounting bracket"},
                {"name": "Swimming Goggles", "price": 16.99, "desc": "Anti-fog swim goggles", "specs": "UV protection, Anti-fog, Adjustable strap, Leak-proof"},
                {"name": "Cooler 50-Quart", "price": 149.99, "desc": "Roto-molded cooler", "specs": "50qt, 5-day ice retention, Bear-resistant, Drain plug"},
                {"name": "Skateboard Complete", "price": 79.99, "desc": "Pro skateboard complete", "specs": "31×8\", ABEC-9 bearings, Maple deck, Grip tape"},
                {"name": "Tennis Racket", "price": 89.99, "desc": "Lightweight tennis racket", "specs": "27\", Graphite, Pre-strung, Grip size 4 3/8, Cover"},
                {"name": "Yoga Block Set", "price": 18.99, "desc": "2-pack yoga blocks with strap", "specs": "High-density foam, 9×6×4\", Lightweight, Strap included"},
            ],
            "Cameras & Drones": [
                {"name": "Mirrorless Camera Kit", "price": 1299.99, "desc": "Professional mirrorless camera with lens", "specs": "24.2MP, 4K video, 18-55mm lens, WiFi, Touchscreen"},
                {"name": "Action Camera 4K", "price": 249.99, "desc": "Waterproof action camera", "specs": "4K 60fps, Waterproof 33ft, WiFi, Image stabilization"},
                {"name": "Camera Tripod", "price": 49.99, "desc": "Professional aluminum tripod", "specs": "65\", Ball head, Quick release, Carry bag, 17.6lbs load"},
                {"name": "Drone with 4K Camera", "price": 799.99, "desc": "GPS drone with gimbal camera", "specs": "4K camera, 3-axis gimbal, 31min flight, GPS, Obstacle avoidance"},
                {"name": "Camera Lens 50mm f/1.8", "price": 199.99, "desc": "Prime portrait lens", "specs": "50mm f/1.8, Autofocus, Full frame compatible, Lens hood"},
                {"name": "Camera Bag", "price": 69.99, "desc": "Professional camera backpack", "specs": "Fits DSLR + 4 lenses, Padded, Rain cover, Laptop compartment"},
                {"name": "LED Ring Light", "price": 89.99, "desc": "18\" LED ring light with stand", "specs": "18\" diameter, Dimmable, 3 color modes, 6ft stand, Phone holder"},
                {"name": "Memory Card 128GB", "price": 39.99, "desc": "High-speed SD card", "specs": "128GB, UHS-I U3, 170MB/s read, 4K video, Class 10"},
                {"name": "Camera Flash Speedlite", "price": 129.99, "desc": "External camera flash", "specs": "TTL, Guide number 58, Swivel head, Wireless trigger"},
                {"name": "Gimbal Stabilizer", "price": 299.99, "desc": "3-axis camera gimbal", "specs": "3-axis stabilization, 2.5lb payload, 12hr battery, App control"},
                {"name": "Drone FPV Goggles", "price": 449.99, "desc": "First-person view goggles", "specs": "1080p display, Head tracking, 2hr battery, DVR recording"},
                {"name": "Camera Cleaning Kit", "price": 19.99, "desc": "Professional cleaning kit", "specs": "Blower, Brush, Cloths, Solution, Swabs, Storage case"},
                {"name": "Softbox Lighting Kit", "price": 149.99, "desc": "Studio lighting set", "specs": "2×20\" softboxes, Stands, Bulbs, Carry bag, Continuous lighting"},
                {"name": "Camera Remote Shutter", "price": 24.99, "desc": "Wireless camera remote", "specs": "100ft range, Bulb mode, Timer, Compatible with most cameras"},
                {"name": "Macro Extension Tubes", "price": 34.99, "desc": "Macro photography extension set", "specs": "Auto-focus, 3-piece set (12/20/36mm), Metal mount"},
                {"name": "Video Microphone", "price": 79.99, "desc": "Shotgun video microphone", "specs": "Super-cardioid, Shock mount, Windscreen, 3.5mm jack"},
                {"name": "Mini Drone", "price": 99.99, "desc": "Foldable mini drone", "specs": "720p camera, 15min flight, Altitude hold, One-key return"},
                {"name": "Camera Shoulder Rig", "price": 189.99, "desc": "DSLR shoulder mount rig", "specs": "Adjustable shoulder pad, Follow focus, Matte box, 15mm rods"},
                {"name": "Portable Photo Studio", "price": 59.99, "desc": "Foldable light box", "specs": "24\", LED lights, 6 backdrops, Foldable, Photography tent"},
                {"name": "ND Filter Set", "price": 79.99, "desc": "Neutral density filter kit", "specs": "ND4/8/16/32, 77mm, Multi-coated, Slim design, Case"},
            ],
            "Women's Bags": [
                {"name": "Leather Tote Bag", "price": 89.99, "desc": "Genuine leather large tote", "specs": "Genuine leather, 15\" laptop fit, Multiple pockets, Detachable strap"},
                {"name": "Crossbody Purse", "price": 49.99, "desc": "Stylish crossbody bag", "specs": "PU leather, Adjustable strap, Multiple compartments, RFID protection"},
                {"name": "Designer Clutch", "price": 39.99, "desc": "Evening clutch with chain", "specs": "Satin finish, Removable chain, Magnetic closure, Multiple colors"},
                {"name": "Backpack Purse", "price": 59.99, "desc": "Convertible backpack handbag", "specs": "Vegan leather, Anti-theft pocket, USB charging port, Lightweight"},
                {"name": "Hobo Shoulder Bag", "price": 69.99, "desc": "Soft hobo style bag", "specs": "Faux leather, Slouchy design, Zipper closure, Inner pockets"},
                {"name": "Satchel Handbag", "price": 79.99, "desc": "Structured satchel bag", "specs": "Top handle + shoulder strap, Organized interior, Metal hardware"},
                {"name": "Weekender Bag", "price": 119.99, "desc": "Travel weekender tote", "specs": "Canvas/leather, Shoe compartment, Trolley sleeve, Water-resistant"},
                {"name": "Belt Bag Fanny Pack", "price": 29.99, "desc": "Trendy waist bag", "specs": "Leather, Adjustable belt, Multiple compartments, Hands-free"},
                {"name": "Bucket Bag", "price": 54.99, "desc": "Drawstring bucket bag", "specs": "Soft leather, Drawstring closure, Adjustable strap, Trendy design"},
                {"name": "Wristlet Wallet", "price": 24.99, "desc": "Zip-around wristlet", "specs": "Card slots, Phone pocket, Wrist strap, RFID blocking"},
                {"name": "Laptop Bag Women", "price": 64.99, "desc": "Professional laptop tote", "specs": "Fits 15.6\" laptop, Padded compartment, Trolley sleeve, Water-resistant"},
                {"name": "Chain Shoulder Bag", "price": 44.99, "desc": "Small bag with chain strap", "specs": "Quilted design, Chain strap, Multiple colors, Compact"},
                {"name": "Canvas Tote", "price": 34.99, "desc": "Large canvas shopping tote", "specs": "Durable canvas, Leather handles, Inner pocket, Beach/shopping"},
                {"name": "Envelope Clutch", "price": 32.99, "desc": "Sleek envelope style clutch", "specs": "Slim design, Magnetic snap, Removable strap, Evening wear"},
                {"name": "Doctor Bag", "price": 94.99, "desc": "Classic doctor's bag style", "specs": "Genuine leather, Structured shape, Double handles, Vintage charm"},
                {"name": "Messenger Bag", "price": 72.99, "desc": "Casual messenger crossbody", "specs": "Canvas/leather trim, Adjustable strap, Flap closure, Pockets"},
                {"name": "Mini Backpack", "price": 42.99, "desc": "Fashion mini backpack", "specs": "Compact size, Dual straps, Front pocket, Convertible straps"},
                {"name": "Beach Bag", "price": 36.99, "desc": "Straw beach tote", "specs": "Natural straw, Spacious, Inner lining, Rope handles, Summer"},
                {"name": "Work Tote", "price": 84.99, "desc": "Professional work bag", "specs": "Structured, Laptop pocket, Organizational pockets, Padded handles"},
                {"name": "Saddle Bag", "price": 58.99, "desc": "Curved saddle crossbody", "specs": "Curved design, Flap closure, Adjustable strap, Vintage style"},
            ],
            "Jewellery & Accessories": [
                {"name": "Sterling Silver Necklace", "price": 49.99, "desc": "Delicate sterling silver chain necklace", "specs": "925 sterling silver, 18\" chain, Pendant, Gift box"},
                {"name": "Leather Watch", "price": 89.99, "desc": "Classic leather strap watch", "specs": "Quartz movement, Genuine leather, Water resistant, Sapphire crystal"},
                {"name": "Hoop Earrings Gold", "price": 34.99, "desc": "14K gold plated hoop earrings", "specs": "14K gold plated, Hypoallergenic, Click closure, 40mm diameter"},
                {"name": "Bracelet Set", "price": 24.99, "desc": "Layered bracelet set of 5", "specs": "Mixed metals, Adjustable, Stackable, Bohemian style"},
                {"name": "Pearl Stud Earrings", "price": 39.99, "desc": "Freshwater pearl studs", "specs": "Genuine freshwater pearls, Sterling silver, 7-8mm, Gift box"},
                {"name": "Sunglasses Polarized", "price": 59.99, "desc": "UV protection polarized sunglasses", "specs": "UV400 protection, Polarized lens, Metal frame, Case included"},
                {"name": "Silk Scarf", "price": 29.99, "desc": "Luxury silk square scarf", "specs": "100% silk, 35×35\", Hand-rolled edges, Multiple patterns"},
                {"name": "Rings Set", "price": 19.99, "desc": "Stackable ring set (8 pieces)", "specs": "Gold/silver tone, Adjustable, Various designs, Midi rings"},
                {"name": "Pendant Necklace", "price": 44.99, "desc": "Crystal pendant necklace", "specs": "Cubic zirconia, 925 silver chain, 16-18\" adjustable, Gift box"},
                {"name": "Cuff Bracelet", "price": 36.99, "desc": "Wide metal cuff bracelet", "specs": "Adjustable, Gold plated, Statement piece, Textured design"},
                {"name": "Anklet", "price": 22.99, "desc": "Dainty chain anklet", "specs": "Sterling silver, Adjustable 9-10\", Charm detail, Beach jewelry"},
                {"name": "Brooch Pin", "price": 18.99, "desc": "Vintage style brooch", "specs": "Crystal embellished, Gold tone, Secure clasp, Gift boxed"},
                {"name": "Hair Clips Set", "price": 16.99, "desc": "Pearl hair clip set", "specs": "Faux pearls, Metal clips, Set of 6, Non-slip"},
                {"name": "Tie Clip", "price": 24.99, "desc": "Men's stainless steel tie clip", "specs": "Stainless steel, 2.2\" length, Polished finish, Gift box"},
                {"name": "Cufflinks", "price": 32.99, "desc": "Luxury cufflinks set", "specs": "Rhodium plated, Gift box, Formal wear, Multiple designs"},
                {"name": "Body Chain", "price": 28.99, "desc": "Layered body chain jewelry", "specs": "Gold tone, Adjustable, Beach/festival wear, Lobster clasp"},
                {"name": "Charm Bracelet", "price": 54.99, "desc": "Sterling silver charm bracelet", "specs": "925 silver, Snake chain, Compatible with charms, 7.5\""},
                {"name": "Statement Necklace", "price": 42.99, "desc": "Bold statement collar necklace", "specs": "Chunky design, Adjustable chain, Party wear, Gift boxed"},
                {"name": "Choker Necklace", "price": 26.99, "desc": "Velvet choker with pendant", "specs": "Velvet ribbon, Adjustable, Crystal pendant, Gothic style"},
                {"name": "Belly Chain", "price": 21.99, "desc": "Waist chain body jewelry", "specs": "Adjustable, Gold tone, Layered design, Beach wear"},
            ],
            "Men's Wear": [
                {"name": "Dress Shirt", "price": 39.99, "desc": "Classic fit dress shirt", "specs": "100% cotton, Wrinkle-free, Button-down collar, Multiple colors"},
                {"name": "Polo Shirt Pack", "price": 49.99, "desc": "3-pack pique polo shirts", "specs": "Cotton blend, Short sleeve, Classic fit, Solid colors"},
                {"name": "Chino Pants", "price": 54.99, "desc": "Slim fit chino trousers", "specs": "Cotton/spandex blend, Flat front, Stretch comfort, Business casual"},
                {"name": "Leather Belt", "price": 29.99, "desc": "Genuine leather dress belt", "specs": "Full grain leather, Reversible, Removable buckle, 1.25\" width"},
                {"name": "Suit Jacket", "price": 149.99, "desc": "Slim fit blazer jacket", "specs": "Wool blend, Two-button, Notch lapel, Lined, Multiple sizes"},
                {"name": "Denim Jeans", "price": 64.99, "desc": "Straight fit denim jeans", "specs": "100% cotton denim, 5-pocket, Regular fit, Multiple washes"},
                {"name": "Dress Socks 6-Pack", "price": 22.99, "desc": "Cushioned dress socks", "specs": "Cotton blend, Reinforced heel/toe, Moisture wicking, Solid colors"},
                {"name": "Cardigan Sweater", "price": 59.99, "desc": "Button-front cardigan", "specs": "Merino wool blend, V-neck, Button closure, Ribbed trim"},
                {"name": "Henley Shirt", "price": 32.99, "desc": "Long sleeve henley", "specs": "Cotton, Button placket, Casual fit, Layering piece"},
                {"name": "Cargo Pants", "price": 49.99, "desc": "Tactical cargo pants", "specs": "Ripstop fabric, Multiple pockets, Reinforced knees, Durable"},
                {"name": "Flannel Shirt", "price": 44.99, "desc": "Plaid flannel button-down", "specs": "100% cotton flannel, Button-down, Chest pockets, Soft"},
                {"name": "Pullover Hoodie", "price": 42.99, "desc": "Fleece pullover hoodie", "specs": "Cotton/poly blend, Kangaroo pocket, Drawstring hood, Ribbed cuffs"},
                {"name": "V-Neck T-Shirt 5-Pack", "price": 34.99, "desc": "Basic v-neck tee pack", "specs": "100% cotton, Short sleeve, Tag-free, Essential basics"},
                {"name": "Sweatpants", "price": 38.99, "desc": "Jogger sweatpants", "specs": "French terry, Elastic waist, Tapered leg, Side pockets"},
                {"name": "Bomber Jacket", "price": 79.99, "desc": "Classic bomber jacket", "specs": "Nylon, Ribbed collar/cuffs, Zipper closure, Lined"},
                {"name": "Formal Vest", "price": 44.99, "desc": "Dress vest waistcoat", "specs": "Polyester, 5-button, Adjustable back, Suit vest"},
                {"name": "Athletic Shorts", "price": 29.99, "desc": "Performance athletic shorts", "specs": "Polyester, Moisture-wicking, Elastic waist, Side pockets"},
                {"name": "Turtleneck Sweater", "price": 48.99, "desc": "Mock neck pullover", "specs": "Acrylic/wool blend, Ribbed turtleneck, Stretchy, Slim fit"},
                {"name": "Tank Top 3-Pack", "price": 24.99, "desc": "Athletic tank tops", "specs": "Cotton blend, Sleeveless, Ribbed, Workout/layering"},
                {"name": "Windbreaker Jacket", "price": 54.99, "desc": "Lightweight windbreaker", "specs": "Water-resistant, Packable, Full zip, Hood, Breathable"},
            ],
            "Home & Living": [
                {"name": "Memory Foam Pillow Set", "price": 49.99, "desc": "2-pack adjustable memory foam pillows", "specs": "Shredded memory foam, Adjustable loft, Cooling cover, Machine washable"},
                {"name": "Duvet Cover Set Queen", "price": 79.99, "desc": "3-piece duvet cover set", "specs": "Queen size, 100% cotton, Zipper closure, Corner ties, 2 pillowcases"},
                {"name": "Area Rug 5x7", "price": 89.99, "desc": "Modern geometric area rug", "specs": "5×7 feet, Non-slip backing, Machine washable, Low pile"},
                {"name": "Curtain Panels Blackout", "price": 39.99, "desc": "Thermal blackout curtains", "specs": "52×84\", 99% light blocking, Energy saving, Grommet top, 2 panels"},
                {"name": "Throw Blanket", "price": 34.99, "desc": "Soft fleece throw blanket", "specs": "50×60\", Ultra-soft, Machine washable, Decorative, Multiple colors"},
                {"name": "Wall Art Canvas Set", "price": 64.99, "desc": "3-piece canvas wall art", "specs": "16×24\" each, Gallery wrapped, Ready to hang, Modern design"},
                {"name": "Table Lamp Set", "price": 54.99, "desc": "2-pack modern table lamps", "specs": "21\" height, Fabric shade, 3-way switch, E26 base, USB ports"},
                {"name": "Bathroom Towel Set", "price": 44.99, "desc": "6-piece bath towel set", "specs": "100% cotton, 2 bath + 2 hand + 2 wash, Absorbent, Multiple colors"},
                {"name": "Kitchen Mat Anti-Fatigue", "price": 29.99, "desc": "Cushioned kitchen floor mat", "specs": "20×39\", 3/4\" thick, Non-slip, Waterproof, Easy clean"},
                {"name": "Storage Ottoman", "price": 69.99, "desc": "Folding storage ottoman", "specs": "15×15×15\", Linen fabric, Collapsible, 300lb capacity, Lid"},
                {"name": "Mirror Wall Mount", "price": 79.99, "desc": "Large rectangular wall mirror", "specs": "24×36\", Aluminum frame, Horizontal/vertical, Mounting hardware"},
                {"name": "Desk Organizer Set", "price": 24.99, "desc": "5-piece desk organization set", "specs": "Mesh metal, Pen holder, Letter tray, File holder, Drawer"},
                {"name": "Plant Stand", "price": 39.99, "desc": "3-tier plant stand", "specs": "Bamboo, 3 shelves, Foldable, Indoor/outdoor, 9 pots capacity"},
                {"name": "Laundry Hamper", "price": 32.99, "desc": "Collapsible laundry basket", "specs": "82L capacity, Aluminum frame, Canvas bag, Handles, Foldable"},
                {"name": "Shower Curtain Set", "price": 19.99, "desc": "Fabric shower curtain with hooks", "specs": "72×72\", Waterproof, Machine washable, 12 hooks, Weighted hem"},
                {"name": "Floating Shelves", "price": 44.99, "desc": "3-piece floating shelf set", "specs": "Rustic wood, 17/13/9\", Invisible brackets, Hardware included"},
                {"name": "Floor Lamp", "price": 89.99, "desc": "Modern arc floor lamp", "specs": "67\" height, 3-way switch, Marble base, Adjustable arm, E26 bulb"},
                {"name": "Decorative Pillows Set", "price": 36.99, "desc": "4-pack throw pillow covers", "specs": "18×18\", Cotton linen, Zipper, Mix & match patterns, Inserts sold separately"},
                {"name": "Coat Rack", "price": 49.99, "desc": "Freestanding coat rack", "specs": "72\" height, 9 hooks, Weighted base, Wood/metal, Scarves/bags"},
                {"name": "Wastebasket Set", "price": 27.99, "desc": "3-piece trash can set", "specs": "Mesh metal, 2 small + 1 large, Bedroom/bathroom/office, Round"},
            ],
            "Beauty & Personal Care": [
                {"name": "Skincare Set 5-Piece", "price": 89.99, "desc": "Complete facial skincare routine", "specs": "Cleanser, toner, serum, moisturizer, eye cream, All skin types"},
                {"name": "Hair Dryer Professional", "price": 79.99, "desc": "Ionic hair dryer with diffuser", "specs": "1875W, Ionic technology, 3 heat/2 speed, Cool shot, Diffuser"},
                {"name": "Makeup Brush Set", "price": 34.99, "desc": "18-piece makeup brush set", "specs": "Synthetic bristles, Wooden handles, Pouch included, Face & eye brushes"},
                {"name": "Electric Toothbrush", "price": 49.99, "desc": "Rechargeable sonic toothbrush", "specs": "40,000 vibrations/min, 5 modes, 4 brush heads, 30-day battery, Timer"},
                {"name": "Facial Cleanser Brush", "price": 39.99, "desc": "Waterproof facial cleansing brush", "specs": "Sonic vibration, Waterproof, Rechargeable, 3 speeds, 2 brush heads"},
                {"name": "Nail Polish Set", "price": 24.99, "desc": "12-color nail polish collection", "specs": "12 colors, Quick dry, Long lasting, Chip resistant, Gift set"},
                {"name": "Hair Straightener", "price": 59.99, "desc": "Ceramic flat iron straightener", "specs": "Titanium ceramic plates, 365°F max, 1\" plates, Auto shut-off"},
                {"name": "Makeup Mirror LED", "price": 44.99, "desc": "Lighted vanity makeup mirror", "specs": "Tri-fold, 21 LED lights, 10X magnification, Touch screen, Adjustable"},
                {"name": "Jade Roller Set", "price": 19.99, "desc": "Facial jade roller and gua sha", "specs": "Natural jade stone, 2-piece set, Cooling, Face sculpting, Gift box"},
                {"name": "Body Lotion Set", "price": 29.99, "desc": "Moisturizing body lotion trio", "specs": "3×8oz bottles, Shea butter, Vitamin E, 3 scents, Hydrating"},
                {"name": "Makeup Palette", "price": 36.99, "desc": "Eyeshadow and blush palette", "specs": "35 colors, Matte & shimmer, High pigment, Mirror included"},
                {"name": "Curling Iron Set", "price": 64.99, "desc": "3-barrel curling wand set", "specs": "3 interchangeable barrels, Ceramic, 410°F max, Heat glove, Stand"},
                {"name": "Sheet Mask Set", "price": 21.99, "desc": "Korean sheet mask variety pack", "specs": "20 masks, 10 types, Hydrating, Anti-aging, Natural extracts"},
                {"name": "Perfume Gift Set", "price": 54.99, "desc": "Women's fragrance collection", "specs": "5 mini perfumes, 0.17oz each, Floral/fruity scents, Gift boxed"},
                {"name": "Eyelash Curler", "price": 12.99, "desc": "Professional eyelash curler", "specs": "Stainless steel, Ergonomic grip, 2 replacement pads, Precision curl"},
                {"name": "Makeup Sponge Set", "price": 14.99, "desc": "Beauty blender sponge set", "specs": "6-pack, Latex-free, Multi-purpose, Expand when wet, Storage case"},
                {"name": "Facial Steamer", "price": 44.99, "desc": "Nano ionic facial steamer", "specs": "Nano steam, Large tank, 10min auto-off, Deep cleansing, Humidifier"},
                {"name": "Lip Gloss Set", "price": 18.99, "desc": "10-piece lip gloss collection", "specs": "10 shades, Non-sticky, Moisturizing, Plumping, Travel size"},
                {"name": "Hair Removal Kit", "price": 69.99, "desc": "IPL hair removal device", "specs": "500,000 flashes, 5 intensity levels, Face & body, Painless, Cordless"},
                {"name": "Foot Spa Massager", "price": 54.99, "desc": "Heated foot bath massager", "specs": "Heating, Bubbles, Massage rollers, Pedicure stones, Temperature control"},
            ],
            "Health & Wellness": [
                {"name": "Blood Pressure Monitor", "price": 39.99, "desc": "Automatic upper arm BP monitor", "specs": "Large LCD, 2 users, 240 memory, Irregular heartbeat, Cuff 8.7-16.5\""},
                {"name": "Pulse Oximeter", "price": 24.99, "desc": "Fingertip pulse oximeter", "specs": "SpO2 & pulse rate, OLED display, Auto shut-off, Lanyard, Battery included"},
                {"name": "Massage Gun", "price": 89.99, "desc": "Deep tissue percussion massager", "specs": "20 speeds, 6 heads, Quiet motor, LCD, 6hr battery, Carry case"},
                {"name": "Digital Scale", "price": 29.99, "desc": "Smart body composition scale", "specs": "Bluetooth, 13 metrics, App sync, 400lb capacity, Auto-calibrate"},
                {"name": "Heating Pad", "price": 34.99, "desc": "Electric heating pad with auto shut-off", "specs": "12×24\", 6 heat settings, 2hr auto-off, Moist/dry heat, Machine washable"},
                {"name": "Acupressure Mat Set", "price": 44.99, "desc": "Acupressure mat and pillow", "specs": "6210 points, Cotton, Foam padding, Carry bag, Pain relief"},
                {"name": "Thermometer Infrared", "price": 34.99, "desc": "No-touch forehead thermometer", "specs": "1-second reading, Fever alarm, Memory recall, Silent mode, °F/°C"},
                {"name": "Nebulizer Machine", "price": 54.99, "desc": "Portable mesh nebulizer", "specs": "Silent operation, Rechargeable, 8ml capacity, Adult & child masks"},
                {"name": "TENS Unit", "price": 49.99, "desc": "Electronic pulse massager", "specs": "16 modes, 8 pads, Rechargeable, LCD, Pain management, Portable"},
                {"name": "Compression Socks 6-Pack", "price": 22.99, "desc": "Graduated compression socks", "specs": "20-30 mmHg, Moisture wicking, Arch support, Unisex, 6 pairs"},
                {"name": "Essential Oil Diffuser", "price": 29.99, "desc": "Ultrasonic aromatherapy diffuser", "specs": "500ml, 7 LED colors, 4 timer settings, Auto shut-off, Whisper quiet"},
                {"name": "Posture Corrector", "price": 24.99, "desc": "Adjustable back brace", "specs": "Adjustable straps, Breathable, Upper back support, Unisex, Washable"},
                {"name": "Pill Organizer Weekly", "price": 14.99, "desc": "7-day pill box organizer", "specs": "Large capacity, 4 times/day, Easy open, BPA-free, Portable"},
                {"name": "Ice Pack Gel", "price": 18.99, "desc": "Hot/cold therapy gel pack", "specs": "11×14\", Reusable, Flexible when frozen, Strap, Microwaveable"},
                {"name": "Foam Roller Vibrating", "price": 64.99, "desc": "Electric vibration foam roller", "specs": "4 speed levels, Rechargeable, High-density, Textured, Carrying case"},
                {"name": "Wrist Brace Pair", "price": 19.99, "desc": "Carpal tunnel wrist support", "specs": "2-pack, Adjustable, Metal splint, Breathable, Day/night use"},
                {"name": "Knee Brace Support", "price": 26.99, "desc": "Compression knee sleeve pair", "specs": "2-pack, Medical grade, Non-slip, Breathable, Multiple sizes"},
                {"name": "Sleep Aid Sound Machine", "price": 34.99, "desc": "White noise sound machine", "specs": "20 sounds, Timer, Memory, Night light, USB/battery powered"},
                {"name": "Resistance Therapy Bands", "price": 16.99, "desc": "Physical therapy resistance bands", "specs": "5 levels, Latex-free, 5ft long, Door anchor, Exercise guide"},
                {"name": "Medicine Cabinet", "price": 49.99, "desc": "Wall-mounted medicine cabinet", "specs": "Mirror door, 3 adjustable shelves, 20×26\", Hardware included"},
            ],
            "Toys, Kids & Babies": [
                {"name": "Building Blocks Set 1000pc", "price": 49.99, "desc": "Classic building blocks mega set", "specs": "1000 pieces, Compatible with major brands, Storage box, Ages 4+"},
                {"name": "Baby Monitor Video", "price": 129.99, "desc": "Video baby monitor with camera", "specs": "5\" display, Night vision, 2-way audio, Temperature, 1000ft range"},
                {"name": "Play Kitchen Set", "price": 89.99, "desc": "Wooden play kitchen with accessories", "specs": "Wooden, Stove/sink/oven, 30+ accessories, Storage, Ages 3+"},
                {"name": "Stroller Travel System", "price": 299.99, "desc": "Car seat and stroller combo", "specs": "Infant car seat, Stroller frame, 5-point harness, Canopy, Storage"},
                {"name": "Activity Table Baby", "price": 54.99, "desc": "Musical activity table", "specs": "Lights & sounds, Removable legs, 70+ songs, Bilingual, 6M+"},
                {"name": "Diaper Bag Backpack", "price": 44.99, "desc": "Multi-function diaper backpack", "specs": "Large capacity, Insulated pockets, Stroller straps, Changing pad"},
                {"name": "Wooden Puzzle Set", "price": 24.99, "desc": "6-pack wooden jigsaw puzzles", "specs": "Age 3-5, 6 puzzles, Wooden, Storage box, Educational"},
                {"name": "Baby Swing", "price": 149.99, "desc": "Portable baby swing", "specs": "6 swing speeds, 10 melodies, Toy bar, AC adapter/battery, 0-9M"},
                {"name": "Play Tent House", "price": 39.99, "desc": "Kids pop-up play tent", "specs": "47×47×51\", Easy setup, Windows, Tunnel, Carry bag, Indoor/outdoor"},
                {"name": "Baby Bottles Set", "price": 29.99, "desc": "Anti-colic baby bottle set", "specs": "6 bottles, BPA-free, Anti-colic, 0-12M, Slow/medium/fast flow"},
                {"name": "Action Figure Set", "price": 34.99, "desc": "Superhero action figures 6-pack", "specs": "6 figures, 6\" tall, Articulated, Accessories, Ages 4+"},
                {"name": "Baby Gym Play Mat", "price": 49.99, "desc": "Musical baby play gym", "specs": "5 toys, Detachable arches, Music & lights, Tummy time, Machine washable"},
                {"name": "Remote Control Car", "price": 44.99, "desc": "RC stunt car", "specs": "2.4GHz, 360° flips, Rechargeable, LED lights, All-terrain, Ages 6+"},
                {"name": "High Chair 3-in-1", "price": 119.99, "desc": "Convertible baby high chair", "specs": "3 modes, 5-point harness, Adjustable height, Tray, 6M-5Y"},
                {"name": "Dollhouse Wooden", "price": 99.99, "desc": "3-story wooden dollhouse", "specs": "3 floors, 6 rooms, 17 furniture pieces, 44\" tall, Ages 3+"},
                {"name": "Baby Pacifiers 6-Pack", "price": 14.99, "desc": "Orthodontic pacifiers set", "specs": "6-pack, BPA-free silicone, Orthodontic, Glow in dark, 0-6M"},
                {"name": "Art Supplies Kit", "price": 32.99, "desc": "Kids art set 150 pieces", "specs": "Crayons, markers, pencils, paints, Paper, Case, Ages 5+"},
                {"name": "Baby Teether Toys", "price": 18.99, "desc": "Silicone teething toys set", "specs": "10 pieces, BPA-free, Freezer safe, Multiple textures, 3M+"},
                {"name": "Board Games Family", "price": 24.99, "desc": "Classic board game collection", "specs": "5 games in 1, 2-4 players, Ages 6+, Travel size, Magnetic"},
                {"name": "Nursery Night Light", "price": 26.99, "desc": "LED night light projector", "specs": "Star projector, 8 colors, Timer, Remote, Music, USB powered"},
            ],
            "Video Games": [
                {"name": "Wireless Gaming Controller", "price": 59.99, "desc": "Universal wireless gamepad", "specs": "Bluetooth, 20hr battery, Vibration, Compatible PC/mobile/console"},
                {"name": "Gaming Headset RGB", "price": 79.99, "desc": "7.1 surround sound headset", "specs": "50mm drivers, Noise-canceling mic, RGB lighting, USB/3.5mm"},
                {"name": "Game Capture Card", "price": 149.99, "desc": "4K game capture device", "specs": "4K 60fps passthrough, 1080p 60fps recording, USB 3.0, Live streaming"},
                {"name": "Racing Wheel & Pedals", "price": 299.99, "desc": "Force feedback racing wheel", "specs": "900° rotation, Force feedback, Pedal set, Multi-platform, Shifter compatible"},
                {"name": "VR Gaming Headset", "price": 399.99, "desc": "Standalone VR headset", "specs": "2K per eye, Inside-out tracking, 128GB storage, Wireless, Controllers"},
                {"name": "Gaming Chair", "price": 199.99, "desc": "Ergonomic racing gaming chair", "specs": "PU leather, Lumbar support, Adjustable arms, 135° recline, 300lb capacity"},
                {"name": "Controller Charging Dock", "price": 24.99, "desc": "Dual controller charging station", "specs": "LED indicators, Overcharge protection, 2 rechargeable batteries, Fast charge"},
                {"name": "Gaming Keyboard", "price": 119.99, "desc": "Mechanical RGB gaming keyboard", "specs": "Mechanical switches, RGB per-key, Macro keys, Wrist rest, USB passthrough"},
                {"name": "Gaming Monitor 27\"", "price": 349.99, "desc": "144Hz curved gaming monitor", "specs": "27\" 1440p, 144Hz, 1ms, Curved, FreeSync, HDR, Adjustable stand"},
                {"name": "Controller Skin Set", "price": 16.99, "desc": "Silicone controller cover + grips", "specs": "2 skins, Thumb grips, Anti-slip, Multiple colors, Easy install"},
                {"name": "Game Storage Case", "price": 29.99, "desc": "Console game organizer", "specs": "Holds 24 games, Protective sleeves, Compact, Dust-proof, Zippered"},
                {"name": "Gaming Mouse Pad RGB", "price": 34.99, "desc": "Extended RGB mouse pad", "specs": "31×12\", RGB lighting, Non-slip, USB powered, Waterproof surface"},
                {"name": "Arcade Fight Stick", "price": 179.99, "desc": "Professional arcade controller", "specs": "Sanwa buttons, 8-way joystick, Tournament legal, Multi-platform"},
                {"name": "Console Cooling Stand", "price": 44.99, "desc": "Vertical stand with cooling fans", "specs": "3 cooling fans, Controller charging, Game storage, USB hub"},
                {"name": "HDMI Switch 4K", "price": 29.99, "desc": "4-port HDMI switcher", "specs": "4K 60Hz, Auto switch, Remote, 4 inputs/1 output, HDCP 2.2"},
                {"name": "Gaming Glasses", "price": 39.99, "desc": "Blue light blocking gaming glasses", "specs": "UV protection, Anti-glare, Reduce eye strain, Lightweight, Case"},
                {"name": "Streaming Microphone", "price": 99.99, "desc": "USB condenser microphone", "specs": "Cardioid pattern, Mute button, Headphone jack, Pop filter, Shock mount"},
                {"name": "Cable Management Kit", "price": 19.99, "desc": "Gaming desk cable organizer", "specs": "Cable clips, Velcro straps, Cable sleeve, Adhesive mounts, 20 pieces"},
                {"name": "Gaming Backpack", "price": 64.99, "desc": "Console travel backpack", "specs": "Fits console + accessories, Padded, Water-resistant, Multiple compartments"},
                {"name": "LED Strip Gaming", "price": 24.99, "desc": "RGB LED strip lights", "specs": "16.4ft, Remote, Music sync, Adhesive, USB powered, 16M colors"},
            ],
            "Hobbies & Books": [
                {"name": "Adult Coloring Book Set", "price": 19.99, "desc": "3-pack adult coloring books", "specs": "Mandalas/nature/patterns, 100+ pages each, Perforated, Thick paper"},
                {"name": "Watercolor Paint Set", "price": 34.99, "desc": "Professional watercolor kit", "specs": "48 colors, 12 brushes, Palette, Paper pad, Mixing tray, Case"},
                {"name": "Jigsaw Puzzle 1000 Piece", "price": 24.99, "desc": "Premium jigsaw puzzle", "specs": "1000 pieces, 27×20\", Thick pieces, Poster included, Storage box"},
                {"name": "Knitting Kit Beginner", "price": 29.99, "desc": "Complete knitting starter set", "specs": "Needles, Yarn, Patterns, Instructions, Accessories, Storage bag"},
                {"name": "Fountain Pen Set", "price": 44.99, "desc": "Calligraphy fountain pen set", "specs": "5 pens, 5 nibs, Ink cartridges, Converter, Gift box, Instructions"},
                {"name": "Scrapbook Album Kit", "price": 32.99, "desc": "DIY scrapbook photo album", "specs": "80 pages, Accessories, Stickers, Corners, Leather cover, 12×12\""},
                {"name": "Chess Set Wooden", "price": 54.99, "desc": "Handcrafted wooden chess set", "specs": "15\" board, Weighted pieces, Felted bottom, Storage drawer"},
                {"name": "Origami Paper Kit", "price": 16.99, "desc": "Origami paper and instruction book", "specs": "500 sheets, Multiple sizes/colors, Instruction book, 30 projects"},
                {"name": "Embroidery Starter Kit", "price": 26.99, "desc": "Cross-stitch embroidery set", "specs": "Threads, Needles, Hoops, Patterns, Fabric, Instructions, Storage"},
                {"name": "Model Building Kit", "price": 39.99, "desc": "Scale model kit with tools", "specs": "Plastic model, Tools, Glue, Paint, Brushes, Instructions, Display stand"},
                {"name": "Journal Notebook Set", "price": 22.99, "desc": "Hardcover journal set of 3", "specs": "A5 size, 200 pages each, Dotted/lined/blank, Elastic band, Pocket"},
                {"name": "Sewing Kit Complete", "price": 49.99, "desc": "Deluxe sewing kit with case", "specs": "126 pieces, Threads, Needles, Scissors, Measuring tape, Storage case"},
                {"name": "Acrylic Paint Set", "price": 38.99, "desc": "Artist acrylic painting set", "specs": "24 colors, Brushes, Canvas panels, Palette, 59ml tubes, Storage box"},
                {"name": "Cookbook Bestseller", "price": 29.99, "desc": "Best-selling cookbook", "specs": "Hardcover, 400+ recipes, Photos, Techniques, Index, Lay-flat binding"},
                {"name": "Gardening Tool Set", "price": 44.99, "desc": "9-piece garden tool kit", "specs": "Trowel, pruners, gloves, Spray bottle, Apron, Steel tools, Carrying tote"},
                {"name": "Sketching Pencil Set", "price": 24.99, "desc": "Professional drawing pencils", "specs": "40 pieces, Graphite/charcoal, Erasers, Sharpener, Paper pad, Case"},
                {"name": "Candle Making Kit", "price": 36.99, "desc": "DIY candle making set", "specs": "Wax, Wicks, Dyes, Scents, Molds, Thermometer, Pouring pot, Instructions"},
                {"name": "Photography Book", "price": 34.99, "desc": "Photography technique guide", "specs": "Hardcover, 300+ pages, Photos, Techniques, Composition, Lighting"},
                {"name": "Calligraphy Practice Set", "price": 28.99, "desc": "Modern calligraphy kit", "specs": "Pens, Nibs, Ink, Practice sheets, Guide book, Tracing paper"},
                {"name": "Telescope Beginner", "price": 89.99, "desc": "Astronomy telescope starter", "specs": "70mm aperture, Tripod, 2 eyepieces, Finder scope, Moon filter, Manual"},
            ],
            "Pet Supplies": [
                {"name": "Dog Food Dry 30lb", "price": 49.99, "desc": "Premium adult dog food", "specs": "30lb bag, Chicken & rice, Grain-free option, All breeds, Made in USA"},
                {"name": "Cat Litter Box Auto", "price": 179.99, "desc": "Self-cleaning litter box", "specs": "Automatic cleaning, Large capacity, Low noise, Odor control, App"},
                {"name": "Pet Carrier Airline", "price": 54.99, "desc": "TSA approved pet carrier", "specs": "Airline approved, Soft-sided, Ventilated, Shoulder strap, 18×11×11\""},
                {"name": "Dog Bed Orthopedic", "price": 64.99, "desc": "Memory foam dog bed large", "specs": "Large 40×30\", Memory foam, Washable cover, Non-slip, Waterproof liner"},
                {"name": "Cat Tree Tower", "price": 89.99, "desc": "Multi-level cat condo", "specs": "54\" tall, 3 platforms, Scratching posts, Hammock, Toys, Plush covering"},
                {"name": "Automatic Pet Feeder", "price": 79.99, "desc": "Programmable pet feeder", "specs": "6L capacity, 4 meals/day, Voice recorder, LCD, Battery backup"},
                {"name": "Pet Water Fountain", "price": 34.99, "desc": "Cat/dog water fountain", "specs": "84oz, Triple filtration, Quiet pump, BPA-free, Dishwasher safe"},
                {"name": "Dog Leash Retractable", "price": 24.99, "desc": "16ft retractable dog leash", "specs": "16ft cord, One-button brake, Anti-slip handle, 110lb, Reflective"},
                {"name": "Cat Scratching Post", "price": 29.99, "desc": "Tall sisal scratching post", "specs": "32\" tall, Sisal rope, Stable base, Hanging toy, Carpet bottom"},
                {"name": "Dog Treats Dental", "price": 19.99, "desc": "Dental chew treats for dogs", "specs": "60 count, Grain-free, Cleans teeth, Freshens breath, All sizes"},
                {"name": "Pet Grooming Kit", "price": 69.99, "desc": "Professional grooming clippers", "specs": "Low noise, Rechargeable, 4 guide combs, Nail trimmer, Scissors, Brush"},
                {"name": "Dog Toys Variety Pack", "price": 26.99, "desc": "10-piece dog toy set", "specs": "Rope, ball, squeaky toys, Durable, Non-toxic, Small-large dogs"},
                {"name": "Cat Toys Interactive", "price": 22.99, "desc": "Electronic cat toy set", "specs": "5 toys, Motion activated, LED lights, Feathers, Batteries, Interactive"},
                {"name": "Pet Hair Remover Roller", "price": 16.99, "desc": "Reusable lint roller", "specs": "Reusable, No refills, Double-sided, Self-cleaning, Handle"},
                {"name": "Dog Collar LED", "price": 18.99, "desc": "Light-up dog collar", "specs": "Rechargeable, 3 modes, Adjustable 12-27\", Waterproof, USB charging"},
                {"name": "Pet Training Pads 100ct", "price": 34.99, "desc": "Puppy training pee pads", "specs": "100 count, 22×22\", Super absorbent, Leak-proof, Odor control"},
                {"name": "Cat Litter Deodorizer", "price": 12.99, "desc": "Natural litter box deodorizer", "specs": "32oz, Baking soda based, Fragrance-free, Safe, 60-day supply"},
                {"name": "Fish Tank 10 Gallon", "price": 89.99, "desc": "Aquarium starter kit", "specs": "10 gallon, LED hood, Filter, Heater, Net, Conditioner, Guide"},
                {"name": "Bird Cage Large", "price": 119.99, "desc": "Parrot bird cage", "specs": "32×23×63\", Bar spacing 3/4\", 4 perches, 2 feeders, Tray, Wheels"},
                {"name": "Hamster Cage Habitat", "price": 54.99, "desc": "Small animal cage", "specs": "24×12×12\", Wire top, Plastic base, Wheel, Bottle, Bowl, Accessories"},
            ],
            "Men's Bags": [
                {"name": "Leather Messenger Bag Men", "price": 89.99, "desc": "Genuine leather laptop messenger", "specs": "Genuine leather, 15.6\" laptop, Adjustable strap, Multiple pockets"},
                {"name": "Backpack Business Men", "price": 64.99, "desc": "Anti-theft laptop backpack", "specs": "TSA friendly, USB port, Water-resistant, 15.6\" laptop, Lockable zipper"},
                {"name": "Duffle Bag Weekender Men", "price": 79.99, "desc": "Canvas travel duffle bag", "specs": "Canvas/leather, 45L capacity, Shoe compartment, Shoulder/hand straps"},
                {"name": "Briefcase Leather Executive", "price": 129.99, "desc": "Executive leather briefcase", "specs": "Full grain leather, 16\" laptop, Combination lock, Organized pockets"},
                {"name": "Gym Bag Sports Men", "price": 39.99, "desc": "Durable sports gym bag", "specs": "40L, Wet/dry compartments, Shoe pocket, Water-resistant, Adjustable strap"},
                {"name": "Sling Bag Crossbody Men", "price": 34.99, "desc": "Casual chest sling bag", "specs": "Water-resistant, USB port, RFID pocket, Adjustable strap, Lightweight"},
                {"name": "Toiletry Bag Men Travel", "price": 24.99, "desc": "Hanging toiletry organizer", "specs": "Water-resistant, Multiple compartments, Hook, Compact, TSA friendly"},
                {"name": "Laptop Sleeve 15.6 Men", "price": 19.99, "desc": "Padded laptop sleeve case", "specs": "15.6\", Neoprene, Water-resistant, Zipper, Front pocket, Slim"},
                {"name": "Belt Bag Tactical Men", "price": 29.99, "desc": "Military style waist bag", "specs": "MOLLE compatible, Water-resistant, Multiple pockets, Adjustable belt"},
                {"name": "Garment Bag Men Business", "price": 44.99, "desc": "Suit garment carrier bag", "specs": "43\", 2 suits, Shoe pockets, Multiple compartments, Shoulder strap"},
                {"name": "Camera Bag Sling Pro", "price": 54.99, "desc": "Professional camera sling bag", "specs": "DSLR + 2 lenses, Padded, Water-resistant, Quick access, Rain cover"},
                {"name": "Laptop Backpack Gaming 17", "price": 74.99, "desc": "Large gaming laptop backpack", "specs": "17.3\" laptop, USB charging, TSA, Water-resistant, Multiple pockets"},
                {"name": "Clutch Bag Men Leather", "price": 32.99, "desc": "Leather wrist clutch", "specs": "Genuine leather, Wrist strap, Card slots, Zipper compartment, RFID"},
                {"name": "Tote Bag Canvas Men", "price": 36.99, "desc": "Large canvas tote bag", "specs": "Canvas, Leather handles, 15\" laptop, Inner pockets, Durable"},
                {"name": "Rolling Duffle Men 26", "price": 119.99, "desc": "Wheeled duffle bag", "specs": "26\", Telescopic handle, Wheels, Multiple pockets, 70L capacity"},
                {"name": "Document Bag Portfolio Men", "price": 49.99, "desc": "Business document organizer", "specs": "Leather, A4 size, Zipper, Pockets, Notepad holder, Pen slots"},
                {"name": "Hiking Daypack Men 30L", "price": 44.99, "desc": "Outdoor hiking backpack", "specs": "30L, Hydration compatible, Rain cover, Multiple pockets, Breathable"},
                {"name": "Laptop Messenger Men 17", "price": 59.99, "desc": "Large laptop messenger bag", "specs": "17\" laptop, Padded, Water-resistant, Adjustable strap, Pockets"},
                {"name": "Money Belt Hidden Security", "price": 18.99, "desc": "Hidden travel money belt", "specs": "RFID blocking, Waterproof, Adjustable, Thin design, 3 pockets"},
                {"name": "Shoe Bag Storage Men", "price": 22.99, "desc": "Waterproof shoe storage bags", "specs": "4-pack, Drawstring, Waterproof, Transparent window, Travel/gym"},
            ],
            "Watches": [
                {"name": "Smartwatch Fitness", "price": 199.99, "desc": "Fitness tracker smartwatch", "specs": "Heart rate, GPS, 5ATM, 7-day battery, Sleep tracking, Notifications"},
                {"name": "Automatic Watch Men", "price": 299.99, "desc": "Mechanical self-winding watch", "specs": "Automatic movement, Stainless steel, Sapphire crystal, 100m water resistant"},
                {"name": "Digital Sports Watch", "price": 49.99, "desc": "Military tactical digital watch", "specs": "Digital, Chronograph, Alarm, Backlight, 50m water resistant, Resin strap"},
                {"name": "Chronograph Watch", "price": 179.99, "desc": "Stainless steel chronograph", "specs": "Quartz movement, Date display, Tachymeter, 100m WR, Metal bracelet"},
                {"name": "Minimalist Watch", "price": 89.99, "desc": "Slim minimalist quartz watch", "specs": "Ultra-thin, Mesh strap, Scratch resistant, Water resistant, Unisex"},
                {"name": "Dive Watch", "price": 249.99, "desc": "Professional diver's watch", "specs": "Automatic, Unidirectional bezel, Luminous, 300m WR, Screw-down crown"},
                {"name": "Wood Watch", "price": 64.99, "desc": "Natural wooden watch", "specs": "Bamboo/Sandalwood, Quartz, Adjustable, Hypoallergenic, Gift box"},
                {"name": "Kids Watch Digital", "price": 24.99, "desc": "Fun kids sports watch", "specs": "Digital, Alarm, Stopwatch, Light, 30m WR, Colorful, Ages 5-12"},
                {"name": "Nurse Watch Clip", "price": 14.99, "desc": "Clip-on nurse fob watch", "specs": "Pin clip, Silicone cover, Glow in dark, Waterproof, Battery included"},
                {"name": "Pocket Watch Vintage", "price": 34.99, "desc": "Classic pocket watch with chain", "specs": "Quartz movement, Chain, Roman numerals, Gift box, Vintage design"},
                {"name": "Solar Watch Atomic", "price": 129.99, "desc": "Solar-powered atomic watch", "specs": "Solar charged, Radio controlled, Titanium, 200m WR, Perpetual calendar"},
                {"name": "Skeleton Watch", "price": 159.99, "desc": "Mechanical skeleton watch", "specs": "See-through design, Automatic, Leather strap, Display back, Exhibition"},
                {"name": "Field Watch Military", "price": 79.99, "desc": "Military field watch", "specs": "Nylon NATO strap, Luminous, Date, 100m WR, Quartz, Rugged"},
                {"name": "Smart Hybrid Watch", "price": 149.99, "desc": "Analog smartwatch hybrid", "specs": "Activity tracking, Notifications, 6-month battery, Analog display"},
                {"name": "Watch Winder Box", "price": 89.99, "desc": "Automatic watch winder case", "specs": "2 watches, Quiet motor, 4 modes, Power adapter, Display window"},
                {"name": "Watch Band Leather", "price": 19.99, "desc": "Genuine leather watch strap", "specs": "Genuine leather, Quick release, 18/20/22mm, Multiple colors, Stitched"},
                {"name": "Watch Repair Kit", "price": 16.99, "desc": "Watch battery replacement tool kit", "specs": "144 batteries, Opener, Tweezers, Pins, Case holder, Storage case"},
                {"name": "Watch Travel Case", "price": 29.99, "desc": "Watch storage organizer", "specs": "8 watches, Zippered, Removable pillows, Compact, Velvet lining"},
                {"name": "Watch Cleaning Kit", "price": 12.99, "desc": "Watch cleaning solution set", "specs": "Solution, Brush, Cloth, Polish, Magnifier, Instructions"},
                {"name": "NATO Watch Strap", "price": 14.99, "desc": "Nylon NATO watch band", "specs": "20mm, Premium nylon, Stainless hardware, Multiple colors, Striped"},
            ],
            "Women's Shoes": [
                {"name": "Running Shoes Women Athletic", "price": 79.99, "desc": "Lightweight running sneakers", "specs": "Breathable mesh, Cushioned sole, Arch support, Memory foam, Multiple colors"},
                {"name": "Ankle Boots Heel Women", "price": 89.99, "desc": "Pointed toe ankle booties", "specs": "3\" heel, Side zipper, Faux leather, Cushioned insole, Stacked heel"},
                {"name": "Slip-On Sneakers Women Casual", "price": 44.99, "desc": "Comfortable slip-on shoes", "specs": "Canvas, Elastic goring, Padded collar, Flexible sole, Machine washable"},
                {"name": "Sandals Flat Women Summer", "price": 34.99, "desc": "Strappy flat sandals", "specs": "Faux leather, Ankle strap, Cushioned footbed, Rubber sole, Summer"},
                {"name": "Ballet Flats Classic", "price": 39.99, "desc": "Classic ballet flat shoes", "specs": "Soft material, Cushioned insole, Flexible, Bow detail, Multiple colors"},
                {"name": "Platform Heels Pumps", "price": 64.99, "desc": "Platform high heel pumps", "specs": "4\" heel, 1\" platform, Pointed toe, Cushioned, Evening wear"},
                {"name": "Winter Boots Knee High", "price": 99.99, "desc": "Knee-high winter boots", "specs": "Faux suede, Side zipper, Faux fur lining, Chunky heel, Water-resistant"},
                {"name": "Wedge Sandals Espadrille", "price": 54.99, "desc": "Espadrille wedge sandals", "specs": "3\" wedge, Ankle strap, Cork wedge, Jute wrap, Summer"},
                {"name": "Mules Backless Slides", "price": 42.99, "desc": "Pointed toe mule slides", "specs": "Low heel, Backless, Pointed toe, Cushioned, Slip-on, Versatile"},
                {"name": "Athletic Shoes Women Training", "price": 69.99, "desc": "Training athletic sneakers", "specs": "Breathable, Non-slip, Shock absorption, Arch support, Gym/running"},
                {"name": "Loafers Women Casual", "price": 49.99, "desc": "Classic penny loafers", "specs": "Faux leather, Cushioned insole, Almond toe, Flat, Casual/professional"},
                {"name": "Rain Boots Waterproof Women", "price": 44.99, "desc": "Waterproof rain boots", "specs": "Waterproof rubber, Pull-on, Mid-calf, Textured sole, Fun patterns"},
                {"name": "Slippers House Women Memory", "price": 24.99, "desc": "Memory foam house slippers", "specs": "Memory foam, Plush lining, Indoor/outdoor, Non-slip, Cozy"},
                {"name": "Sneakers White Platform", "price": 59.99, "desc": "Classic white sneakers", "specs": "Leather, Lace-up, Cushioned, Versatile, Platform sole, Trendy"},
                {"name": "Hiking Boots Women Waterproof", "price": 94.99, "desc": "Waterproof hiking boots", "specs": "Waterproof, Ankle support, Vibram sole, Lace-up, Trail ready"},
                {"name": "Dress Pumps Classic Women", "price": 54.99, "desc": "Classic pointed toe pumps", "specs": "3\" heel, Pointed toe, Cushioned, Faux patent leather, Professional"},
                {"name": "Gladiator Sandals Strappy", "price": 38.99, "desc": "Strappy gladiator sandals", "specs": "Multiple straps, Back zipper, Flat, Faux leather, Bohemian"},
                {"name": "Slip-On Sneakers Canvas Women", "price": 32.99, "desc": "Canvas slip-on shoes", "specs": "Canvas, Elastic sides, Cushioned, Classic style, Multiple prints"},
                {"name": "Chelsea Boots Women Ankle", "price": 74.99, "desc": "Ankle Chelsea boots", "specs": "Elastic sides, Pull-on, Low heel, Faux leather, Versatile"},
                {"name": "Flip Flops Women Comfort", "price": 19.99, "desc": "Comfortable flip flop sandals", "specs": "Yoga mat footbed, Arch support, Thong style, Lightweight, Beach"},
            ],
            "Automotive": [
                {"name": "Dash Cam 4K", "price": 129.99, "desc": "Front and rear dash camera", "specs": "4K front/1080p rear, Night vision, G-sensor, Loop recording, 128GB card"},
                {"name": "Car Vacuum Cordless", "price": 49.99, "desc": "Portable car vacuum cleaner", "specs": "Cordless, 6000Pa suction, Washable filter, LED, Attachments, Rechargeable"},
                {"name": "Jump Starter Portable", "price": 89.99, "desc": "Battery jump starter power bank", "specs": "2000A peak, USB ports, LED flashlight, 12000mAh, Air compressor"},
                {"name": "Tire Inflator Digital", "price": 34.99, "desc": "Portable air compressor", "specs": "150PSI, Digital gauge, Auto shut-off, LED light, 12V, Adaptors"},
                {"name": "Car Phone Mount", "price": 24.99, "desc": "Wireless charging car mount", "specs": "15W fast charge, Auto-clamping, 360° rotation, Dashboard/vent"},
                {"name": "Seat Covers Set", "price": 54.99, "desc": "Full set car seat covers", "specs": "Universal fit, Leather, Front + rear, Headrest covers, Airbag compatible"},
                {"name": "Floor Mats All-Weather", "price": 44.99, "desc": "Heavy-duty car floor mats", "specs": "4-piece set, All-weather, Odorless, Trim-to-fit, Deep channels"},
                {"name": "Bluetooth FM Transmitter", "price": 19.99, "desc": "Wireless car audio adapter", "specs": "Bluetooth 5.0, Dual USB, Hands-free, LED display, Aux out"},
                {"name": "Backup Camera", "price": 64.99, "desc": "Wireless backup camera kit", "specs": "Wireless, Night vision, Waterproof, 5\" monitor, Wide angle"},
                {"name": "Steering Wheel Cover", "price": 16.99, "desc": "Leather steering wheel cover", "specs": "Microfiber leather, 15\", Non-slip, Breathable, Universal fit"},
                {"name": "Car Wax Kit", "price": 29.99, "desc": "Complete car detailing kit", "specs": "Wash, wax, polish, Applicators, Microfiber towels, Spray bottle"},
                {"name": "Trunk Organizer", "price": 39.99, "desc": "Collapsible car trunk organizer", "specs": "3 compartments, Collapsible, Non-slip bottom, Reinforced handles"},
                {"name": "Windshield Sun Shade", "price": 14.99, "desc": "Foldable sun visor protector", "specs": "Universal fit, Foldable, Reflective, UV protection, Easy storage"},
                {"name": "LED Headlight Bulbs", "price": 59.99, "desc": "H11 LED headlight conversion", "specs": "6000K white, 12000LM, Plug & play, Cooling fan, 50,000hr life"},
                {"name": "Car Air Freshener", "price": 12.99, "desc": "Vent clip air freshener set", "specs": "4-pack, Essential oils, Adjustable, Long-lasting, Multiple scents"},
                {"name": "OBD2 Scanner", "price": 79.99, "desc": "Diagnostic code reader", "specs": "OBD2, Live data, Check engine, Clear codes, Color screen, All protocols"},
                {"name": "USB Car Charger", "price": 18.99, "desc": "Dual port fast car charger", "specs": "36W, Dual USB, Fast charge, LED, Universal, Compact, Metal"},
                {"name": "Car Trash Can", "price": 22.99, "desc": "Waterproof car garbage bin", "specs": "Leak-proof, Lid closure, Storage pockets, Adjustable strap, Washable"},
                {"name": "Door Edge Guards", "price": 16.99, "desc": "Car door edge protection", "specs": "16ft, U-shape, Flexible, Self-adhesive, Scratch protection, Trim-to-fit"},
                {"name": "License Plate Frame", "price": 11.99, "desc": "Stainless steel plate frame", "specs": "2-pack, Stainless steel, Rust-free, Screw caps, Standard size"},
            ],
            "Dining, Travel & Services": [
                {"name": "Dinnerware Set 16-Piece", "price": 89.99, "desc": "Porcelain dinner plate set", "specs": "Service for 4, Plates/bowls/mugs, Dishwasher safe, Chip resistant"},
                {"name": "Flatware Set 20-Piece", "price": 44.99, "desc": "Stainless steel silverware set", "specs": "Service for 4, 18/10 stainless, Dishwasher safe, Mirror finish"},
                {"name": "Stemless Wine Glasses", "price": 24.99, "desc": "Wine glass set of 6", "specs": "15oz capacity, Crystal clear, Dishwasher safe, Elegant design"},
                {"name": "Travel Pillow Memory Foam", "price": 29.99, "desc": "Neck pillow for airplane", "specs": "Memory foam, Adjustable, Washable cover, Compact, Carry pouch"},
                {"name": "Luggage Set 3-Piece", "price": 199.99, "desc": "Hard-shell suitcase set", "specs": "20/24/28\", Spinner wheels, TSA lock, Expandable, Lightweight"},
                {"name": "Packing Cubes 6-Set", "price": 24.99, "desc": "Travel packing organizers", "specs": "6 sizes, Mesh top, Durable, Compression, Lightweight, Multiple colors"},
                {"name": "Insulated Lunch Bag", "price": 19.99, "desc": "Adult lunch box cooler", "specs": "Insulated, Leak-proof, Front pocket, Adjustable strap, Fits containers"},
                {"name": "Travel Adapter Universal", "price": 29.99, "desc": "International power adapter", "specs": "150+ countries, 4 USB ports, Fuse protected, Compact, Dual voltage"},
                {"name": "Tablecloth Waterproof", "price": 18.99, "desc": "Spill-proof table cloth", "specs": "60×84\", Waterproof, Stain resistant, Wrinkle-free, Easy clean"},
                {"name": "Bento Lunch Box", "price": 26.99, "desc": "Leak-proof compartment lunch box", "specs": "3 compartments, BPA-free, Microwave safe, Utensils, Insulated bag"},
                {"name": "Travel Jewelry Organizer", "price": 16.99, "desc": "Portable jewelry case", "specs": "Compact, Compartments, Zipper, Ring slots, Earring holders, Soft lining"},
                {"name": "Camping Cookware Set", "price": 49.99, "desc": "Outdoor cooking pot set", "specs": "10 pieces, Non-stick, Foldable handles, Mesh bag, Lightweight, Compact"},
                {"name": "Passport Holder RFID", "price": 14.99, "desc": "Travel passport wallet", "specs": "RFID blocking, Card slots, Pen holder, Boarding pass, Leather"},
                {"name": "Food Storage Containers", "price": 34.99, "desc": "Glass meal prep containers", "specs": "10-pack, Glass, Snap lids, Microwave/dishwasher safe, BPA-free"},
                {"name": "Thermal Coffee Mug", "price": 22.99, "desc": "Insulated travel coffee mug", "specs": "16oz, Stainless steel, Leak-proof lid, 6hr hot, Handle, Car holder"},
                {"name": "Picnic Blanket Waterproof", "price": 32.99, "desc": "Extra large picnic mat", "specs": "79×79\", Waterproof backing, Foldable, Carry handle, Sand-proof"},
                {"name": "Salad Bowl Set", "price": 36.99, "desc": "Large salad serving bowl set", "specs": "Large bowl + servers, Bamboo, 12\", Eco-friendly, Food safe"},
                {"name": "Luggage Scale Digital", "price": 12.99, "desc": "Portable baggage scale", "specs": "110lb capacity, LCD, Tare function, Auto-off, Hook, Compact"},
                {"name": "Travel Bottles TSA", "price": 11.99, "desc": "Leak-proof travel containers", "specs": "TSA approved, 3oz bottles, Silicone, 10-pack, Labels, Zipper bag"},
                {"name": "Bamboo Cutting Board", "price": 28.99, "desc": "Large bamboo cutting board", "specs": "17×12\", Bamboo, Juice groove, Eco-friendly, Knife-friendly"},
            ],
            "Men's Shoes": [
                {"name": "Dress Shoes Oxford", "price": 79.99, "desc": "Leather oxford dress shoes", "specs": "Genuine leather, Lace-up, Cushioned insole, Formal, Multiple widths"},
                {"name": "Running Shoes Men", "price": 89.99, "desc": "Cushioned running sneakers", "specs": "Breathable mesh, Air cushion, Memory foam, Arch support, Lightweight"},
                {"name": "Chelsea Boots Leather", "price": 99.99, "desc": "Men's Chelsea ankle boots", "specs": "Genuine leather, Elastic sides, Pull-on, Rubber sole, Versatile"},
                {"name": "Casual Sneakers", "price": 64.99, "desc": "Lifestyle casual sneakers", "specs": "Canvas/leather, Lace-up, Padded collar, Rubber sole, Everyday wear"},
                {"name": "Hiking Boots Waterproof", "price": 119.99, "desc": "Men's hiking boots", "specs": "Waterproof, Ankle support, Vibram sole, Breathable, Trail ready"},
                {"name": "Loafers Slip-On", "price": 69.99, "desc": "Penny loafer dress shoes", "specs": "Leather, Slip-on, Cushioned, Business casual, Multiple colors"},
                {"name": "Work Boots Steel Toe", "price": 129.99, "desc": "Safety steel toe work boots", "specs": "Steel toe, Slip-resistant, Oil-resistant, 8\" shaft, Durable leather"},
                {"name": "Sandals Leather", "price": 44.99, "desc": "Adjustable leather sandals", "specs": "Genuine leather, Adjustable straps, Contoured footbed, Cork sole"},
                {"name": "Boat Shoes", "price": 74.99, "desc": "Classic boat deck shoes", "specs": "Leather, Lace-up, Non-marking sole, Cushioned, Water-resistant"},
                {"name": "Basketball Shoes", "price": 94.99, "desc": "High-top basketball sneakers", "specs": "Ankle support, Cushioned, Non-slip, Breathable, Court performance"},
                {"name": "Winter Boots Insulated", "price": 109.99, "desc": "Waterproof winter boots", "specs": "Insulated, Waterproof, Faux fur lining, -20°F rated, Grip sole"},
                {"name": "Slippers Men", "price": 29.99, "desc": "Memory foam house slippers", "specs": "Memory foam, Plush lining, Indoor/outdoor, Non-slip, Moccasin style"},
                {"name": "Training Shoes", "price": 79.99, "desc": "Cross-training athletic shoes", "specs": "Stable base, Breathable, Versatile, Gym/weights, Rope guard"},
                {"name": "Flip Flops", "price": 24.99, "desc": "Comfort flip flop sandals", "specs": "Cushioned footbed, Arch support, Durable, Lightweight, Beach/pool"},
                {"name": "Chukka Boots", "price": 89.99, "desc": "Suede chukka desert boots", "specs": "Suede leather, Ankle height, Lace-up, Crepe sole, Casual"},
                {"name": "Golf Shoes", "price": 99.99, "desc": "Spikeless golf shoes", "specs": "Waterproof, Spikeless, Breathable, Cushioned, Traction, Performance"},
                {"name": "Slip-On Sneakers", "price": 54.99, "desc": "Canvas slip-on shoes", "specs": "Canvas, Elastic goring, Padded, Classic style, Casual comfort"},
                {"name": "Driving Moccasins", "price": 59.99, "desc": "Leather driving loafers", "specs": "Soft leather, Rubber pebbles, Slip-on, Flexible, Driving shoe"},
                {"name": "Rain Boots", "price": 49.99, "desc": "Waterproof rubber rain boots", "specs": "Waterproof rubber, Pull-on, Mid-calf, Traction sole, All-weather"},
                {"name": "Monk Strap Shoes", "price": 94.99, "desc": "Leather monk strap dress shoes", "specs": "Genuine leather, Double buckle, Formal, Cushioned, Unique style"},
            ],
            "Travel & Luggage": [
                {"name": "Carry-On Suitcase Hardside 22", "price": 89.99, "desc": "Hardside spinner carry-on", "specs": "22\", 4 spinner wheels, TSA lock, Lightweight, Expandable, Durable"},
                {"name": "Travel Backpack Flight Approved", "price": 69.99, "desc": "Flight approved travel backpack", "specs": "40L, Laptop compartment, Shoe pocket, USB port, Water-resistant"},
                {"name": "Toiletry Bag Hanging Large", "price": 26.99, "desc": "Large hanging toiletry organizer", "specs": "Multiple compartments, Hook, Water-resistant, Compact, TSA friendly"},
                {"name": "Compression Packing Bags", "price": 19.99, "desc": "Space saver packing bags", "specs": "15 sizes, Roll compression, Reusable, Waterproof, Organize clothes"},
                {"name": "Neck Wallet RFID Pouch", "price": 14.99, "desc": "Hidden travel neck pouch", "specs": "RFID blocking, Waterproof, Adjustable strap, Multiple pockets, Thin"},
                {"name": "Shoe Bags Travel Organizer", "price": 16.99, "desc": "Waterproof shoe storage bags", "specs": "6-pack, Drawstring, Transparent window, Waterproof, Organize luggage"},
                {"name": "Luggage Strap Adjustable", "price": 12.99, "desc": "Adjustable luggage straps", "specs": "2-pack, Heavy-duty, Quick release, Bright colors, 79\" adjustable"},
                {"name": "Travel Pillow Inflatable Neck", "price": 18.99, "desc": "Compact inflatable neck pillow", "specs": "Inflatable, Compact, Washable cover, Airplane/car, Carry pouch"},
                {"name": "Duffel Bag Foldable Travel", "price": 54.99, "desc": "Foldable travel duffel bag", "specs": "50L, Foldable, Shoulder strap, Water-resistant, Multiple pockets"},
                {"name": "Cable Organizer Electronics", "price": 22.99, "desc": "Electronics travel organizer", "specs": "Multiple compartments, Elastic loops, Waterproof, Compact, USB cable"},
                {"name": "Luggage Cover Suitcase", "price": 18.99, "desc": "Suitcase protective cover", "specs": "Elastic, Multiple sizes, Washable, Scratch protection, Fits 20-28\""},
                {"name": "Travel First Aid Emergency", "price": 29.99, "desc": "Compact emergency medical kit", "specs": "200 pieces, Compact case, Essential supplies, TSA approved, Organized"},
                {"name": "Garment Bag Suit Carrier", "price": 39.99, "desc": "Tri-fold garment carrier", "specs": "40\", 2-3 suits, Shoe pockets, Water-resistant, Shoulder strap, Breathable"},
                {"name": "Money Belt Travel RFID", "price": 13.99, "desc": "Hidden money belt RFID", "specs": "RFID blocking, Waterproof, Adjustable, Passport size, Thin design"},
                {"name": "Luggage Tag Identifier Set", "price": 9.99, "desc": "Durable luggage tags 4-pack", "specs": "4-pack, Stainless steel, Privacy flap, Adjustable loop, Bright colors"},
                {"name": "Travel Jewelry Organizer Case", "price": 24.99, "desc": "Small jewelry travel organizer", "specs": "Compact, Ring holder, Necklace bar, Zippered, Soft lining, Portable"},
                {"name": "Beach Bag Oversized Mesh", "price": 32.99, "desc": "Oversized beach tote bag", "specs": "Extra large, Mesh, Beach toy pockets, Sand-proof, Shoulder straps"},
                {"name": "Foldable Tote Shopping Bag", "price": 14.99, "desc": "Reusable shopping tote", "specs": "Foldable, Water-resistant, Large capacity, Attached pouch, Lightweight"},
                {"name": "Laundry Bag Mesh Travel", "price": 11.99, "desc": "Mesh laundry travel bag", "specs": "2-pack, Drawstring, Breathable mesh, Machine washable, Compact"},
                {"name": "Car Roof Cargo Bag", "price": 89.99, "desc": "Waterproof roof cargo bag", "specs": "15 cubic ft, Waterproof, Straps included, Foldable, Universal fit"},
            ],
            "Miscellaneous": [
                {"name": "Umbrella Windproof", "price": 29.99, "desc": "Compact automatic travel umbrella", "specs": "Auto open/close, Windproof, 10 ribs, Water-repellent, Compact"},
                {"name": "Reusable Water Bottle", "price": 24.99, "desc": "Insulated stainless steel bottle", "specs": "32oz, Double-wall vacuum, BPA-free, 24hr cold, Wide mouth"},
                {"name": "Multi-Tool Pocket", "price": 34.99, "desc": "Multi-function pocket tool", "specs": "15 functions, Stainless steel, Pliers, Knife, Screwdriver, Sheath"},
                {"name": "Flashlight Tactical LED", "price": 22.99, "desc": "Rechargeable tactical flashlight", "specs": "1200 lumens, Rechargeable, 5 modes, Zoom, Water-resistant, Clip"},
                {"name": "Emergency Kit Car", "price": 59.99, "desc": "Roadside emergency kit", "specs": "125 pieces, Jumper cables, Tools, First aid, Warning triangle, Bag"},
                {"name": "Key Finder Bluetooth", "price": 24.99, "desc": "Item tracker tag 4-pack", "specs": "Bluetooth, 200ft range, Replaceable battery, App, Sound/light alert"},
                {"name": "Hand Sanitizer Gel 64oz", "price": 18.99, "desc": "Bulk hand sanitizer refill", "specs": "64oz, 75% alcohol, Pump bottle, Aloe vera, Moisturizing"},
                {"name": "Duct Tape Heavy Duty", "price": 12.99, "desc": "Multi-purpose duct tape", "specs": "4-pack, 1.88\"×60yds, Heavy-duty, Waterproof, Multiple colors"},
                {"name": "Bungee Cord Set", "price": 16.99, "desc": "Assorted bungee cords 24-pack", "specs": "24 pieces, Multiple sizes, Heavy-duty, Hooks, Carabiners, Organized"},
                {"name": "Tarp Heavy Duty", "price": 34.99, "desc": "Waterproof poly tarp", "specs": "12×16ft, Waterproof, Reinforced corners, Grommets, Multi-use"},
                {"name": "Rope Nylon 50ft", "price": 19.99, "desc": "Braided utility rope", "specs": "50ft, 5/16\", 1200lb capacity, Rot-resistant, Multi-purpose"},
                {"name": "Carabiner Clips 12-Pack", "price": 13.99, "desc": "Aluminum carabiner set", "specs": "12-pack, Aluminum, D-shape, Spring gate, Multiple sizes, Keychain"},
                {"name": "Measuring Tape 25ft", "price": 14.99, "desc": "Self-locking tape measure", "specs": "25ft, Auto-lock, Belt clip, Metric/imperial, Magnetic hook"},
                {"name": "Utility Knife Set", "price": 18.99, "desc": "Retractable utility knife 2-pack", "specs": "2 knives, 10 blades, Auto-lock, Rubber grip, Heavy-duty"},
                {"name": "Cable Ties 1000-Pack", "price": 16.99, "desc": "Nylon zip ties assorted", "specs": "1000 pieces, Multiple sizes, Self-locking, Nylon, Organize cables"},
                {"name": "Velcro Strips Roll", "price": 14.99, "desc": "Heavy-duty hook and loop tape", "specs": "15ft×2\", Industrial strength, Self-adhesive, Cut to size, Black"},
                {"name": "Super Glue 12-Pack", "price": 11.99, "desc": "Instant adhesive glue", "specs": "12 tubes, Precision tip, Instant bond, Multi-purpose, Dries clear"},
                {"name": "WD-40 Multi-Use", "price": 8.99, "desc": "Lubricant spray can", "specs": "12oz, Multi-purpose, Lubricates, Protects, Smart straw, Household"},
                {"name": "Ratchet Tie-Downs", "price": 29.99, "desc": "Heavy-duty ratchet straps", "specs": "4-pack, 15ft×1\", 1500lb capacity, Ratchet, Soft loops, Cargo"},
                {"name": "Tool Box Portable", "price": 39.99, "desc": "Plastic tool storage box", "specs": "20\", Removable tray, Organizers, Metal latches, Handle, Durable"},
            ],
        }

        total_created = 0
        categories = Category.objects.filter(is_active=True)
        
        for category in categories:
            category_name = category.name
            if category_name in products_data:
                self.stdout.write(f'\nPopulating {category_name}...')
                
                for product_data in products_data[category_name]:
                    # Random stock and units sold for realism
                    stock = random.randint(10, 200)
                    units_sold = random.randint(0, 500)
                    
                    product, created = Product.objects.get_or_create(
                        name=product_data["name"],
                        category=category,
                        defaults={
                            'description': product_data["desc"],
                            'specifications': product_data["specs"],
                            'price': product_data["price"],
                            'stock': stock,
                            'units_sold': units_sold,
                            'is_active': True
                        }
                    )
                    
                    if created:
                        total_created += 1
                        self.stdout.write(self.style.SUCCESS(f'  + {product.name}'))
                    else:
                        self.stdout.write(f'  - {product.name} (already exists)')
            else:
                self.stdout.write(self.style.WARNING(f'No data for category: {category_name}'))
        
        self.stdout.write(self.style.SUCCESS(f'\n{"="*70}'))
        self.stdout.write(self.style.SUCCESS(f'Successfully created {total_created} products!'))
        self.stdout.write(self.style.SUCCESS(f'Total products in database: {Product.objects.count()}'))
        self.stdout.write(self.style.SUCCESS(f'{"="*70}'))
