# Generated by Django 6.0.1 on 2026-02-02 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=40)),
                ('interaction_type', models.CharField(choices=[('view_category', 'View Category'), ('view_product', 'View Product'), ('add_to_cart', 'Add to Cart'), ('update_cart', 'Update Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_started', 'Checkout Started'), ('order_placed', 'Order Placed'), ('search', 'Search'), ('review_submitted', 'Review Submitted'), ('product_favorited', 'Product Favorited')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Quantity for cart operations', null=True)),
                ('search_query', models.CharField(blank=True, help_text='Search query text', max_length=255)),
                ('page_url', models.CharField(blank=True, help_text='URL of the page', max_length=500)),
                ('referrer_url', models.CharField(blank=True, help_text='Referrer URL', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional interaction data', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='store.category')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='store_useri_timesta_551485_idx'), models.Index(fields=['interaction_type', '-timestamp'], name='store_useri_interac_db1695_idx'), models.Index(fields=['user', '-timestamp'], name='store_useri_user_id_7d9699_idx'), models.Index(fields=['session_key', '-timestamp'], name='store_useri_session_6fc810_idx'), models.Index(fields=['product', '-timestamp'], name='store_useri_product_dbe08a_idx')],
            },
        ),
    ]
