# Generated by Django 6.0.1 on 2026-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of customer reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_summary_cons',
            field=models.TextField(blank=True, help_text='Cons extracted from reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was last generated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_summary_pros',
            field=models.TextField(blank=True, help_text='Pros extracted from reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_summary_review_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews included in the summary'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_summary_sentiment',
            field=models.CharField(blank=True, help_text='Overall sentiment: positive, neutral, or negative', max_length=20),
        ),
    ]
