# Generated by Django 6.0.1 on 2026-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_review_summary_product_review_summary_cons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dynamic_description',
            field=models.TextField(blank=True, help_text='AI-generated engaging product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='dynamic_description_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the dynamic description was last generated', null=True),
        ),
    ]
